### ISSUE TITLE
Feature request - multiple destinations output

### ISSUE THREAD

**Issue by craigrallen** [hkapanen/ais-forwarder#1]
Hi,

The plugin is really good and simple to use. I would like to have the option to forward to multiple destinations, similar to the AIS-Reporter plugin. Add multiple IP address and port numbers.

Is this something that could be achieved?

**Comment by hkapanen** [comment]
Yes, this should be quite straight-forward to do. Unfortunately, I don't need this myself, so no promises when (if ever) I get to it. However, pull requests are welcome.

**Comment by craigrallen** [comment]
Hi,  thanks for getting back to me. I don't know how to code so I'll guess I'll need to wait :)

**Comment by hwater** [comment]
If you find the time in these lockdowns, i would also like to forward the positions of other ships to vesselfinder AND marinetraffic. holger at the danube

**Comment by itemir** [comment]
+1 for this ask

**Comment by Ianknx** [comment]
Multiple destinations please.

**Comment by hkapanen** [comment]
Merged #5
