### ISSUE TITLE
Feature request: Maximum range for valid positions

### ISSUE THREAD

**Issue by Haimana** [hkapanen/ais-forwarder#11]
Hello,

And thank you for your useful plugin.
I'm using it to send data to MarineTraffic, where my boat is acting like a roaming station.
In the last period (since the Ukraine/Russia war started) some GPS signals are jammed, and my AIS receive wrong position for some ships.
Because of these invalid positions, MT set my AIS station as offline, even over 90% of data is accurate.

So, I want to ask if is possible to add a feature for filtering (forward reporting) only ships which are closer than some distance which can be real data. Right now, I receive good data 30Nm around me but because the GPS jammers some ships are reported 250Nm away which is wrong.

Thank you,
Seb

![image](https://github.com/hkapanen/ais-forwarder/assets/60715651/c333bb7a-01d5-43f8-bfa9-2b909c8bc8d7)

**Comment by tkurki** [comment]
This plugin does not "see" into the data it is passing, it is just blindly forwarding all the AIS messages. This means that the plugin can not filter the data.

The way to do this would be to add a way for the nmea0183-to-signalk to emit messages that contain
- vessel identity (MMSI)
- a whole AIS message, consisting of multiple nmea0183 sentences

This is doable, but just work in nmea0183-to-signalk and probably on the server's streams module.

**Comment by Haimana** [comment]
Thanks for reply. I'll close this for now, maybe this feature will be added sometime. Or they will stop GPS jamming ... 
Fair wind to all
