### ISSUE TITLE
SignalK 1.43.1 - depricated setProviderStatus

### ISSUE THREAD

**Issue by dirkwa** [hkapanen/ais-forwarder#8]
Note on cmdline out at server startup.

![image](https://user-images.githubusercontent.com/86628605/158844734-8b3c4169-b2e4-494f-9402-5c31b4dd1382.jpeg)

**Comment by hkapanen** [comment]
PR welcome!

**Comment by dirkwa** [comment]
Sorry, what does PR mean?

**Comment by hkapanen** [comment]
Pull Request -- a change proposal to the code.
